# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-28 03:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='imagenesprojectos',
            options={'verbose_name': 'Imagen', 'verbose_name_plural': 'Imagenes'},
        ),
        migrations.AlterModelOptions(
            name='projecto',
            options={'verbose_name': 'Projecto', 'verbose_name_plural': 'Projectos'},
        ),
        migrations.AlterField(
            model_name='imagenesprojectos',
            name='projecto',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='imagenes', to='home.Projecto'),
        ),
    ]
